### ISSUE TITLE
Nucleo ST32F303 board support - needs #define LEDPIN 0x05

### ISSUE THREAD

**Issue by Andy2No** [cnlohr/minimal_stm32f303#1]
Thanks for this example - it was just the sort of thing I was looking for to get started with a Nucleo STM32F303 board, and plain GCC.

However, the onboard LED is on a different pin, on that board - which baffled me until I worked out how the pin mapping works, and that you'd clearly written this for different hardware.

On the Nucleo boards, it's on the pin corresponding to D13, on the Arduino compatible header sockets.  On the NUCLEO-F303RE, that's PA05, so the line in systems.h needs to be edited to:

#define LEDPIN 0x05

Other than that, it works fine.

**Comment by cnlohr** [comment]
hmm... I am OK with changing the default pin.
